on:
  repository_dispatch:
    types: [minicran_trigger]
  push:
    branches: [master, main]
    paths-ignore:
    - '.github/**'

name: minicran

jobs:
  minicran:
    name: Minicran deployment
    runs-on: ubuntu-20.04
    steps:
      - name: Dispatch to minicran
        run: |
          curl \
            -X POST -f \
            -H "Authorization: token ${{ secrets.GH_PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/LaCapitale/dsops-r-minicran/dispatches \
            -d '{"event_type":"minicran_trigger", "client_payload": {"repository":"'"$GITHUB_REPOSITORY"'", "ref":"'"$GITHUB_REF"'"}}'
